//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoDienTu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int IDAdmin { get; set; }
        [Required]
        public string TenAdmin { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Phone]
        public string SDT { get; set; }        
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}
