//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoDienTu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MaGiamGia
    {
        public string IDMaGiamGia { get; set; }
        [Required]
        public string TenMaGiamGia { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayBatDauGiamGia { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayKetThucGiamGia { get; set; }
        [Range(0,int.MaxValue)]
        public Nullable<int> SoTienGiam { get; set; }
    }
}
